# Generated by Django 5.2.3 on 2026-08-01 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('vehicle_types', models.CharField(help_text='Comma separated types, e.g. Car,Bike,Truck', max_length=200)),
                ('base_hourly_price', models.DecimalField(decimal_places=2, help_text='Price for first base hours', max_digits=10)),
                ('additional_hour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_hour_after', models.PositiveIntegerField(default=1, help_text='Apply additional price after X hours')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Staff'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_managed', to=settings.AUTH_USER_MODEL)),
                ('exit_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exits_managed', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.parkingzone')),
            ],
        ),
    ]
