# Generated by Django 5.2.3 on 2026-08-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='extra_hours_step',
            field=models.PositiveIntegerField(default=1, help_text='Charge applies per every X extra hours'),
        ),
    ]
