# Generated by Django 5.2.3 on 2026-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingzone_extra_hours_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If checked, zone is 100% free'),
        ),
    ]
