# Generated by Django 5.2.3 on 2026-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingzone_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerecord',
            name='entry_photo',
            field=models.ImageField(blank=True, null=True, upload_to='entry_photos/'),
        ),
    ]
