# Generated by Django 5.2.3 on 2026-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_manage_payments',
            new_name='can_collect_cash',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='can_search',
            new_name='can_download_reports',
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_zones',
            field=models.BooleanField(default=False),
        ),
    ]
